
import React from 'react';
import { Twitter, Youtube, Instagram, Sun, Moon, Languages, Star, Search, ChevronDown, Link as LinkIcon, ExternalLink, ClipboardCopy, Home, Users, MessageSquare, Image as ImageIcon, Link2, UserCircle, Award, X, Check, ZoomIn, ZoomOut, PowerOff, RotateCcw, Map as MapIcon, RefreshCw, Layers, SearchX, Tag, Filter, ArrowUp, ArrowDown, AlertCircle, Vote as VoteIcon, History, Clock, Trophy, Lock, LogOut, Eye, Plus, Edit, Trash, Save, Key, ShieldCheck, ArrowLeft, ArrowRight, FileText, Calendar, Trash2, Settings, Ban, RotateCw, Minus, CheckCircle2, Upload, AlertTriangle, FolderOpen, PenTool, EyeOff, Loader2, Database, Radio, Play, Bell, BellOff, Snowflake, Video, Tv, UserCheck, MoreVertical, XCircle, RefreshCcw, Circle, Wifi, WifiOff, List, UserPlus, CornerUpRight, Activity, Send } from 'lucide-react';

const Kick = (props: React.ImgHTMLAttributes<HTMLImageElement>) => (
    <img src="https://i.postimg.cc/65CJczDK/1726118265kick-logo-white.png" alt="Kick Logo" {...props} className={`${props.className || ''} object-contain`} />
);
const Tiktok = (props: React.ImgHTMLAttributes<HTMLImageElement>) => (
    <img src="https://i.postimg.cc/hhWshLr1/tiktok-512.png" alt="TikTok Logo" {...props} />
);
const Discord = (props: React.ImgHTMLAttributes<HTMLImageElement>) => (
    <img src="https://i.postimg.cc/FFMX0wCJ/pngkey-com-discord-png-200938.png" alt="Discord Logo" {...props} className={`${props.className || ''} object-contain`} />
);

export const Icons = {
  Twitter: (props: React.SVGProps<SVGSVGElement>) => <Twitter {...props} />,
  Kick: (props: React.ImgHTMLAttributes<HTMLImageElement>) => <Kick {...props} />,
  YouTube: (props: React.SVGProps<SVGSVGElement>) => <Youtube {...props} />,
  TikTok: (props: React.ImgHTMLAttributes<HTMLImageElement>) => <Tiktok {...props} />,
  Instagram: (props: React.SVGProps<SVGSVGElement>) => <Instagram {...props} />,
  Discord: (props: React.ImgHTMLAttributes<HTMLImageElement>) => <Discord {...props} />,
  Sun: (props: React.SVGProps<SVGSVGElement>) => <Sun {...props} />,
  Moon: (props: React.SVGProps<SVGSVGElement>) => <Moon {...props} />,
  Languages: (props: React.SVGProps<SVGSVGElement>) => <Languages {...props} />,
  Star: (props: React.SVGProps<SVGSVGElement>) => <Star {...props} />,
  Search: (props: React.SVGProps<SVGSVGElement>) => <Search {...props} />,
  ChevronDown: (props: React.SVGProps<SVGSVGElement>) => <ChevronDown {...props} />,
  Link: (props: React.SVGProps<SVGSVGElement>) => <LinkIcon {...props} />,
  ExternalLink: (props: React.SVGProps<SVGSVGElement>) => <ExternalLink {...props} />,
  ClipboardCopy: (props: React.SVGProps<SVGSVGElement>) => <ClipboardCopy {...props} />,
  Home: (props: React.SVGProps<SVGSVGElement>) => <Home {...props} />,
  Users: (props: React.SVGProps<SVGSVGElement>) => <Users {...props} />,
  Map: (props: React.SVGProps<SVGSVGElement>) => <MapIcon {...props} />,
  Threads: (props: React.SVGProps<SVGSVGElement>) => <MessageSquare {...props} />,
  Images: (props: React.SVGProps<SVGSVGElement>) => <ImageIcon {...props} />,
  Links: (props: React.SVGProps<SVGSVGElement>) => <Link2 {...props} />,
  Tags: (props: React.SVGProps<SVGSVGElement>) => <Tag {...props} />,
  Tag: (props: React.SVGProps<SVGSVGElement>) => <Tag {...props} />,
  Credits: (props: React.SVGProps<SVGSVGElement>) => <Award {...props} />,
  X: (props: React.SVGProps<SVGSVGElement>) => <X {...props} />,
  Check: (props: React.SVGProps<SVGSVGElement>) => <Check {...props} />,
  SearchPlus: (props: React.SVGProps<SVGSVGElement>) => <ZoomIn {...props} />,
  SearchMinus: (props: React.SVGProps<SVGSVGElement>) => <ZoomOut {...props} />,
  PowerOff: (props: React.SVGProps<SVGSVGElement>) => <PowerOff {...props} />,
  RotateCcw: (props: React.SVGProps<SVGSVGElement>) => <RotateCcw {...props} />,
  Refresh: (props: React.SVGProps<SVGSVGElement>) => <RefreshCw {...props} />,
  Layers: (props: React.SVGProps<SVGSVGElement>) => <Layers {...props} />,
  SearchX: (props: React.SVGProps<SVGSVGElement>) => <SearchX {...props} />,
  Filter: (props: React.SVGProps<SVGSVGElement>) => <Filter {...props} />,
  ArrowUp: (props: React.SVGProps<SVGSVGElement>) => <ArrowUp {...props} />,
  ArrowDown: (props: React.SVGProps<SVGSVGElement>) => <ArrowDown {...props} />,
  AlertCircle: (props: React.SVGProps<SVGSVGElement>) => <AlertCircle {...props} />,
  Vote: (props: React.SVGProps<SVGSVGElement>) => <VoteIcon {...props} />,
  Votes: (props: React.SVGProps<SVGSVGElement>) => <VoteIcon {...props} />, 
  History: (props: React.SVGProps<SVGSVGElement>) => <History {...props} />,
  Clock: (props: React.SVGProps<SVGSVGElement>) => <Clock {...props} />,
  Trophy: (props: React.SVGProps<SVGSVGElement>) => <Trophy {...props} />,
  Lock: (props: React.SVGProps<SVGSVGElement>) => <Lock {...props} />,
  LogOut: (props: React.SVGProps<SVGSVGElement>) => <LogOut {...props} />,
  Eye: (props: React.SVGProps<SVGSVGElement>) => <Eye {...props} />,
  EyeOff: (props: React.SVGProps<SVGSVGElement>) => <EyeOff {...props} />,
  Plus: (props: React.SVGProps<SVGSVGElement>) => <Plus {...props} />,
  Edit: (props: React.SVGProps<SVGSVGElement>) => <Edit {...props} />,
  Trash: (props: React.SVGProps<SVGSVGElement>) => <Trash {...props} />,
  Save: (props: React.SVGProps<SVGSVGElement>) => <Save {...props} />,
  Key: (props: React.SVGProps<SVGSVGElement>) => <Key {...props} />,
  ShieldCheck: (props: React.SVGProps<SVGSVGElement>) => <ShieldCheck {...props} />,
  ArrowLeft: (props: React.SVGProps<SVGSVGElement>) => <ArrowLeft {...props} />,
  ArrowRight: (props: React.SVGProps<SVGSVGElement>) => <ArrowRight {...props} />,
  UserCircle: (props: React.SVGProps<SVGSVGElement>) => <UserCircle {...props} />,
  FileText: (props: React.SVGProps<SVGSVGElement>) => <FileText {...props} />,
  Calendar: (props: React.SVGProps<SVGSVGElement>) => <Calendar {...props} />,
  Trash2: (props: React.SVGProps<SVGSVGElement>) => <Trash2 {...props} />,
  Settings: (props: React.SVGProps<SVGSVGElement>) => <Settings {...props} />,
  Ban: (props: React.SVGProps<SVGSVGElement>) => <Ban {...props} />,
  RotateCw: (props: React.SVGProps<SVGSVGElement>) => <RotateCw {...props} />,
  Minus: (props: React.SVGProps<SVGSVGElement>) => <Minus {...props} />,
  CheckCircle2: (props: React.SVGProps<SVGSVGElement>) => <CheckCircle2 {...props} />,
  Upload: (props: React.SVGProps<SVGSVGElement>) => <Upload {...props} />,
  AlertTriangle: (props: React.SVGProps<SVGSVGElement>) => <AlertTriangle {...props} />,
  FolderOpen: (props: React.SVGProps<SVGSVGElement>) => <FolderOpen {...props} />,
  PenTool: (props: React.SVGProps<SVGSVGElement>) => <PenTool {...props} />,
  Loader2: (props: React.SVGProps<SVGSVGElement>) => <Loader2 {...props} />,
  Database: (props: React.SVGProps<SVGSVGElement>) => <Database {...props} />,
  Radio: (props: React.SVGProps<SVGSVGElement>) => <Radio {...props} />,
  Play: (props: React.SVGProps<SVGSVGElement>) => <Play {...props} />,
  Bell: (props: React.SVGProps<SVGSVGElement>) => <Bell {...props} />,
  BellOff: (props: React.SVGProps<SVGSVGElement>) => <BellOff {...props} />,
  Snowflake: (props: React.SVGProps<SVGSVGElement>) => <Snowflake {...props} />,
  Video: (props: React.SVGProps<SVGSVGElement>) => <Video {...props} />,
  Tv: (props: React.SVGProps<SVGSVGElement>) => <Tv {...props} />,
  Live: (props: React.SVGProps<SVGSVGElement>) => <Tv {...props} />, 
  UserCheck: (props: React.SVGProps<SVGSVGElement>) => <UserCheck {...props} />,
  MoreVertical: (props: React.SVGProps<SVGSVGElement>) => <MoreVertical {...props} />,
  XCircle: (props: React.SVGProps<SVGSVGElement>) => <XCircle {...props} />,
  RefreshCcw: (props: React.SVGProps<SVGSVGElement>) => <RefreshCcw {...props} />,
  Circle: (props: React.SVGProps<SVGSVGElement>) => <Circle {...props} />,
  Wifi: (props: React.SVGProps<SVGSVGElement>) => <Wifi {...props} />,
  WifiOff: (props: React.SVGProps<SVGSVGElement>) => <WifiOff {...props} />,
  List: (props: React.SVGProps<SVGSVGElement>) => <List {...props} />,
  UserPlus: (props: React.SVGProps<SVGSVGElement>) => <UserPlus {...props} />,
  CornerUpRight: (props: React.SVGProps<SVGSVGElement>) => <CornerUpRight {...props} />,
  Send: (props: React.SVGProps<SVGSVGElement>) => <Send {...props} />,
  Analyzing: (props: React.SVGProps<SVGSVGElement>) => <Activity {...props} />,
  Activity: (props: React.SVGProps<SVGSVGElement>) => <Activity {...props} />,
};
